//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by pb.rc
//
#define IDC_STATIC                      -1
#define IDR_RT_MANIFEST                 1
#define IDD_MAIN                        101
#define IDS_EXCEPTION                   102
#define IDS_LOG                         103
#define IDD_LOG                         103
#define IDS_TIME                        105
#define IDI_MAIN                        106
#define IDS_RANGE                       106
#define IDI_DISABLED                    107
#define IDS_SOURCE                      107
#define IDD_STARTUP_LAST                107
#define IDI_HTTPDISABLED                108
#define IDS_DESTINATION                 108
#define IDS_BLOCK                       109
#define IDD_LISTS                       110
#define IDS_ALLOW                       110
#define IDS_FILE                        111
#define IDD_CREATELIST                  111
#define IDS_TYPE                        112
#define IDD_UPDATELISTS                 112
#define IDS_DESCRIPTION                 113
#define IDR_TRAYMENU                    113
#define IDS_UPDATING                    114
#define IDR_SPLASH                      114
#define IDS_LISTSNOTUPDATED             114
#define IDS_DONEUPDATING                115
#define IDR_BINARY2                     115
#define IDD_SPLASH                      116
#define IDS_STARTUPWIZ                  116
#define IDD_STARTUP_FIRST               117
#define IDS_SELECTLISTS                 117
#define IDD_STARTUP_LISTS               118
#define IDS_SELECTLISTSSUB              118
#define IDD_STARTUP_UPDATES             119
#define IDS_CUSTOMIZELISTS              119
#define IDS_CUSTOMIZELISTSSUB           120
#define IDD_ABOUT                       120
#define IDS_AUTOUPDATES                 121
#define IDR_LICENSE                     121
#define IDD_EDITLIST                    121
#define IDS_AUTOUPDATESSUB              122
#define IDS_PBACTIVE                    123
#define IDD_LIST                        123
#define IDS_PBDISABLED                  124
#define IDD_LOADING                     124
#define IDS_UPDATINGPB                  125
#define IDS_UPDATEPB                    125
#define IDS_UPDATINGLISTS               126
#define IDS_LISTSUPTODATE               127
#define IDR_BINARY4                     127
#define IDS_LISTSNOTUPTODATE            128
#define IDR_LISTSCONTEXT                129
#define IDS_ALLOWXFOR15MIN              129
#define IDS_ALLOWXPERM                  130
#define IDR_LISTCONTEXT                 130
#define IDS_STARTIP                     131
#define IDS_ENDIP                       132
#define IDD_FOO                         132
#define IDD_ADDLIST                     132
#define IDS_CLOSE                       133
#define IDS_PBOPEN                      134
#define IDD_HISTORY                     134
#define IDS_PBOPENTEXT                  135
#define IDS_P2P                         136
#define IDD_HISTORY_EXPORT              136
#define IDS_ADS                         137
#define IDR_HISTORYMENU                 137
#define IDS_SPY                         138
#define IDD_HISTORY_CALENDAR            138
#define IDD_HISTORY_FIND                139
#define IDS_EDU                         140
#define IDD_SETTINGS_FIRST              140
#define IDS_COPYXTOCLIPBOARD            141
#define IDD_SETTINGS_SECOND             141
#define IDS_INVALIDAPPID                142
#define IDS_ERROR                       143
#define IDS_UPDATEAVAILABLE             144
#define IDS_ALLOWXFORONEHOUR            145
#define IDS_UPDATEAVAILABLETEXT         146
#define IDS_DOWNLOADINGPCNT             146
#define IDS_PERMALLOW                   147
#define IDS_PERMALLOWS                  147
#define IDS_STATISTICS                  148
#define IDS_TOTALBLOCKED                149
#define IDS_BLOCKSPERDAY                150
#define IDS_BLOCKSPERHOUR               151
#define IDS_ERRORCONTACTING             152
#define IDS_CLEARLOG                    153
#define IDS_NEEDUPDATE                  154
#define IDS_OPEN                        155
#define IDS_EDIT                        156
#define IDS_NEEDUPDATETEXT              157
#define IDS_FILENOTFOUND                158
#define IDS_FILENOTFOUNDTEXT            159
#define IDS_BLOCKED                     160
#define IDS_ALLOWED                     161
#define IDS_HTTPERROR                   162
#define IDS_HTTPERRORTEXT               163
#define IDS_MAKESTATIC                  164
#define IDS_REMOVE                      165
#define IDS_MAKESTATICTEXT              166
#define IDS_WARNING                     167
#define IDS_NEEDADMINTEXT               168
#define IDS_NEEDADMIN                   169
#define IDS_INVALIDURL                  170
#define IDS_INVALIDURLTEXT              171
#define IDS_UNCAUGHTTEXT                172
#define IDS_UNCAUGHT                    173
#define IDS_TIMEOUTTEXT                 174
#define IDS_PBUPDATE                    174
#define IDS_TIMEOUT                     175
#define IDS_PBUPDATETEXT                175
#define IDS_ACTION                      176
#define IDS_PROTOCOL                    177
#define IDS_ALL                         178
#define IDS_HTTPIS                      179
#define IDS_UPDATESTATUS                180
#define IDS_DISABLE                     181
#define IDS_ENABLE                      182
#define IDS_BLOCKHTTP                   183
#define IDS_ALLOWHTTP                   184
#define IDS_STARTUP_LAST                185
#define IDS_STARTUP_LISTS               186
#define IDS_STARTUP_OPTIMIZATION        187
#define IDS_STARTUP_UPDATES             188
#define IDS_OPTIMIZATION                189
#define IDS_HTTPBLOCKS                  189
#define IDS_OPTIMIZATIONSUB             190
#define IDS_ALLBLOCKS                   190
#define IDS_GENCACHE                    191
#define IDS_CONNECTING                  192
#define IDS_NOUPDATENEEDED              193
#define IDS_FINISHED                    194
#define IDS_NOUPDATEAVAIL               195
#define IDS_TASK                        196
#define IDS_STATUS                      197
#define IDS_DOWNLOADING                 198
#define IDS_NONEAVAILABLE               199
#define IDS_ABORTED                     200
#define IDS_ERRORCONTACTINGWHY          201
#define IDS_CLOSEX                      202
#define IDS_HIDINGTEXT                  203
#define IDS_HIDING                      204
#define IDS_EXPORTING                   205
#define IDS_BLOCKXFOR15MIN              206
#define IDS_BLOCKXFORONEHOUR            207
#define IDS_BLOCKXPERM                  208
#define IDS_PERMBLOCKS                  209
#define IDS_CLEARDBTEXT                 210
#define IDS_CLEARDB                     211
#define IDS_ERRFILEOPEN                 212
#define IDS_ERRCURL                     213
#define IDS_BADBACKUPTEXT               214
#define IDS_BADBACKUP                   215
#define IDS_RESTOREBACKUPTEXT           216
#define IDS_RESTOREBACKUP               217
#define IDS_RESTORING                   218
#define IDS_BACKINGUP                   219
#define IDS_EXCEPTIONTEXT               220
#define IDS_SEARCH                      221
#define IDS_CALENDAR                    222
#define IDS_CAUGHTUNKNOWNTEXT           223
#define IDS_HISTORYERR                  224
#define IDS_HISTORYOPEN                 225
#define IDS_ARCHIVEREMOVE               226
#define IDS_DONOTHING                   227
#define IDS_INVALIDFILETEXT             228
#define IDS_INVALIDFILE                 229
#define IDS_LISTERR                     230
#define IDS_LISTERRTEXT                 231
#define IDS_DRIVERERR                   232
#define IDS_DRIVERERRTEXT               233
#define IDS_FILEOPENERR                 234
#define IDS_FILEOPENERRTEXT             235
#define IDS_GENUINE                     236
#define IDS_LOGALLOWED                  236
#define IDS_GENUINETEXT                 237
#define IDS_LOGBLOCKED                  237
#define IDS_LOGBOTH                     238
#define IDS_LOGNONE                     239
#define IDS_UNCAUGHTWIN32TEXT           240
#define IDS_DRIVERERRWIN32TEXT          241
#define IDS_UNSIGNEDDRIVERTEXT          242
#define IDS_NEEDSVCSERR                 243
#define IDS_NEEDSVCSERRTEXT             244
#define IDS_UNEXPCONTACTINGWHY          245
#define IDS_DNLISTFAILEDVERIFY          246
#define IDS_PGALREADYRUNNING            247
#define IDS_PGALREADYRUNNINGTEXT        248
#define IDS_PREVREL                     249
#define IDS_PREVREL268TEXT              250
#define IDS_CONFERR                     251
#define IDS_CONFERRTEXT                 252
#define IDS_LISTSAN_TITLE               253
#define IDS_LISTSAN_UNFRIENDLY          254
#define IDS_LISTSAN_NOTIBL              255
#define IDS_LISTSAN_WRONG               256
#define IDS_LISTSAN_DEFAULT             257
#define IDS_LISTSAN_DEFAULT_NIBL        258
#define IDS_LISTSAN_EXACTDUPE           259
#define IDS_LISTSAN_DEFDUPE             260
#define IDS_LISTSAN_DIFFDUPE            261
#define IDS_EXITWHILEBLOCKING           262
#define IDS_EXITWHILEBLOCKINGTEXT       263
#define IDS_PREVREL341TEXT_DEL          264
#define IDS_PREVREL341TEXT_MAX          265
#define IDS_PREVREL341TEXT_BOTH         266
#define IDS_PORTSETTINGS                267
#define IDS_PREVREL411TEXT_WEBEX        268
#define IDS_PREVREL411TEXT_BOGON        269
#define IDS_VERIFYING					270
#define IDC_TABS                        1001
#define IDC_LIST                        1002
#define IDC_UPDATE                      1003
#define IDC_ENABLED_STATUS              1005
#define IDC_UPDATE_STATUS               1006
#define IDC_ENABLED_ICON                1007
#define IDC_UPDATE_ICON                 1008
#define IDC_EVERYDAY                    1009
#define IDC_EVERYOTHERDAY               1010
#define IDC_EVERYWEEK                   1011
#define IDC_EVERYXDAYS                  1012
#define IDC_UPDATEINTERVAL              1013
#define IDC_UPDATEINTERVALSPIN          1014
#define IDC_PEERBLOCK                   1015
#define IDC_LISTS                       1016
#define IDC_LOGSIZE                     1017
#define IDC_LOGSIZESPIN                 1018
#define IDC_LOGTOFILE                   1019
#define IDC_LOGFILE                     1020
#define IDC_BROWSE                      1021
#define IDC_NORMAL                      1022
#define IDC_AGGRESSIVE                  1023
#define IDC_REMOVE                      1025
#define IDC_ADD                         1026
#define IDC_EDIT                        1027
#define IDC_ADDFILE                     1028
#define IDC_FILE                        1029
#define IDC_ADDURL                      1031
#define IDC_URL                         1032
#define IDC_BLOCK                       1034
#define IDC_ALLOW                       1035
#define IDC_DESCRIPTION                 1036
#define IDC_PROGRESS                    1037
#define IDC_PICTURE                     1039
#define IDC_P2P                         1040
#define IDC_ADS                         1041
#define IDC_SPYWARE                     1042
#define IDC_EDUCATIONAL                 1044
#define IDC_CUSTOM                      1045
#define IDC_CUSTOMSPIN                  1051
#define IDC_TITLE                       1054
#define IDC_FILEPROGRESS                1055
#define IDC_HOMEPAGE                    1056
#define IDC_FORUMS                      1057
#define IDC_LICENSE                     1058
#define IDC_LIST1                       1059
#define IDC_OPEN                        1064
#define IDC_BLOCKSPERHOUR               1066
#define IDC_BLOCKSPERDAY                1067
#define IDC_TOTALBLOCKED                1068
#define IDC_BARGRAPH                    1071
#define IDC_RADIO1                      1072
#define IDC_NEVER                       1072
#define IDC_CREATE                      1075
#define IDC_SEARCH                      1079
#define IDC_SEARCHTEXT                  1080
#define IDC_NEXT                        1081
#define IDC_BUTTON2                     1082
#define IDC_PREV                        1082
#define IDC_HISTORY                     1082
#define IDC_STARTWITHWINDOWS            1083
#define IDC_SHOWSPLASH                  1084
#define IDC_STARTMINIMIZED              1085
#define IDC_CLEAR                       1086
#define IDC_CALENDAR                    1087
#define IDC_REMOVEHISTORY               1089
#define IDC_HISTORYLIFE                 1090
#define IDC_HISTORYLIFESPIN             1091
#define IDC_LOGALLOWED                  1092
#define IDC_EDIT1                       1093
#define IDC_RANGENAME                   1093
#define IDC_AUTOUPDATETIME              1093
#define IDC_HTTP_STATUS                 1101
#define IDC_LAST_UPDATE                 1102
#define IDC_ENABLE                      1105
#define IDC_HTTP                        1106
#define IDC_COMBO1                      1108
#define IDC_PROTOCOLLIST                1108
#define IDC_BLOCKHTTP                   1111
#define IDC_MONTHCALENDAR1              1113
#define IDC_RECOMMEND                   1114
#define IDC_ABORT                       1115
#define IDC_CLOSE                       1116
#define IDC_FROM                        1119
#define IDC_FROMDATE                    1120
#define IDC_TO                          1121
#define IDC_TODATE                      1122
#define IDC_PROTOCOL                    1123
#define IDC_ACTION                      1124
#define IDC_ACTIONLIST                  1125
#define IDC_TODAY                       1126
#define IDC_RANGE                       1135
#define IDC_SOURCE                      1136
#define IDC_SOURCEIP                    1137
#define IDC_DEST                        1138
#define IDC_DESTIP                      1139
#define IDC_FIND                        1140
#define IDC_CALTABS                     1141
#define IDC_SHOWALLOWED                 1146
#define IDC_COLORCODE                   1147
#define IDC_CLEANUP                     1151
#define IDC_CLEANUPTIME                 1152
#define IDC_CLEANUPTIMESPIN             1153
#define IDC_ARCHIVETO                   1155
#define IDC_NOTIFY                      1156
#define IDC_NOTIFYON                    1157
#define IDC_BLINKTRAY                   1158
#define IDC_USEPROXY                    1159
#define IDC_CHECKPB                     1162
#define IDC_CHECKLISTS                  1163
#define IDC_AUTOUPDATE                  1164
#define IDC_AUTOUPDATETIMESPIN          1165
#define IDC_PROXYHOST                   1166
#define IDC_SOCKS5                      1167
#define IDC_AUTOCLOSE                   1168
#define IDC_AUTOCLOSETIME               1169
#define IDC_AUTOCLOSETIMESPIN           1170
#define IDC_HIDETRAY                    1171
#define IDC_HIDEONCLOSE                 1172
#define IDC_NOTIFYWINDOW                1173
#define IDC_ONTOP                       1174
#define IDC_ATEXT                       1175
#define IDC_ABG                         1176
#define IDC_BTEXT                       1177
#define IDC_BBG                         1178
#define IDC_HTTPTEXT                    1179
#define IDC_HTTPBG                      1180
#define IDC_PROGRESS1                   1181
#define IDC_UPDATE_AT_STARTUP           1182
#define IDC_P2PLIST                     1183
#define IDC_SPYLIST                     1184
#define IDC_ADSLIST                     1185
#define IDC_EDULIST                     1186
#define IDC_MORELISTS                   1187
#define IDC_DEFGROUP                    1188
#define IDC_SAVE                        1189
#define IDC_OPENP2P                     1190
#define IDC_OPENSPY                     1191
#define IDC_OPENADS                     1192
#define IDC_OPENEDU                     1193
#define IDC_MAXHISTORYSIZE              1194
#define IDC_MAXHISTORYSIZESPIN          1195
#define IDD_EDITPORTS                   1196
#define IDD_PORTPROFILE                 1197
#define IDC_EDITPORTS                   1198
#define IDC_ADDPORTPROFILE              1199
#define IDC_PORTS                       1200
#define IDC_HTTPPORT                    1201
#define IDC_FTPPORT                     1202
#define IDC_SMTPPORT                    1203
#define IDC_POP3PORT                    1204
#define IDC_PORTNAME                    1205
#define IDC_PORTPORTS                   1206
#define IDC_DESTINATIONPORT             1207
#define IDC_SOURCEPORT                  1208
#define IDC_BOTHPORT                    1209
#define IDS_SETTINGS_FIRST              1210
#define IDS_SETTINGS_SECOND             1211

#define ID_TRAY_PEERBLOCK               40001
#define ID_TRAY_ENABLED                 40002
#define ID_TRAY_DISABLED                40003
#define ID_TRAY_BLOCKHTTP               40004
#define ID_TRAY_ABOUT                   40005
#define ID_TRAY_EXIT                    40006
#define ID_CONTEXT_EXPORTTOP2B          40008
#define ID_CONTEXT_OPEN                 40010
#define ID_CONTEXT_EDIT                 40011
#define ID_CONTEXT_ALLOWFOR15MINUTES    40012
#define ID_CONTEXT_ALLOWFORONEHOUR      40013
#define ID_CONTEXT_ALLOWPERMANENTLY     40014
#define ID_Menu                         40016
#define ID_CONTEXT_EXPORTTO             40017
#define ID_TRAY_ALWAYSONTOP             40018
#define ID_TRAY_HIDETRAYICON            40019
#define ID_FILE_EXPORTTO                40021
#define ID_FILE_CLEARDATABASE           40023
#define ID_FILE_EXIT                    40024
#define ID_FILE_RESTOREDATABASE         40025
#define ID_FILE_BACKUPDATABASE          40026
#define ID_TRAY_HELP                    40027
#define ID_TRAY_SUPPORT                 40028
#define ID_TRAY_TEMPALLOWHTTP15         40029
#define ID_TRAY_TEMPALLOWHTTP60         40030

// PeerBlock window messages
#define WM_PORTSETTINGSCHANGE           (WM_APP+1)

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         40027
#define _APS_NEXT_CONTROL_VALUE         1182
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
