//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by pg3.rc
//
#define IDS_TIME                        101
#define IDS_ADDRESS                     102
#define IDR_ENABLE                      102
#define IDS_COUNT                       103
#define IDR_MAINMENU                    103
#define IDR_ABOUT                       103
#define IDS_LABEL                       104
#define IDS_ENABLED                     105
#define IDD_ADDLIST                     105
#define IDS_DISABLED                    106
#define IDD_LISTMANAGER                 106
#define IDD_LISTS                       106
#define IDS_ENABLEDHTTP                 107
#define IDI_ICON1                       107
#define IDI_LISTMANAGER                 107
#define IDI_LISTCONFIG                  107
#define IDS_OFN_ALLTYPES                108
#define IDI_ICON2                       108
#define IDI_REFRESH                     108
#define IDS_UNCAUGHTTITLE               109
#define IDB_REFRESH                     109
#define IDS_UNCAUGHTINSTRUCTION         110
#define IDR_BINARY1                     110
#define IDS_UNCAUGHTCONTENT             111
#define IDR_BINARY2                     111
#define IDS_SHOWREPORTINFO              112
#define IDS_HIDEREPORTINFO              113
#define IDS_FINDSOLUTIONS               114
#define IDI_DOPEFISH                    114
#define IDS_REPORTINFO                  115
#define IDS_REPORTINFOWIN               116
#define IDI_PREFS                       116
#define IDS_REPORTERROR                 117
#define IDI_INFO                        117
#define IDS_DONTREPORT                  118
#define IDD_QUICKLIST                   118
#define IDS_OFN_TEXTTYPES               119
#define IDD_ADDTEMP                     119
#define IDS_OFN_EMULETYPE               120
#define IDD_APPLIST                     120
#define IDS_OFN_BINARYTYPE              121
#define IDD_ABOUT                       121
#define IDS_OFN_ALLFILES                122
#define IDS_COMMDLG_ERROR               123
#define IDD_ADDAPP                      123
#define IDS_REPORTINFOCOMMDLG           124
#define IDD_GRAPHS                      124
#define IDS_LISTMANAGER                 125
#define IDD_ADDPROFILE                  125
#define IDS_CHECKUPDATES                126
#define IDD_EDITPROFILES                126
#define IDS_ABOUTPEERGUARDIAN           127
#define IDS_ABOUTCONTENT                128
#define IDS_OPTIONS                     129
#define IDS_LISTS                       130
#define IDS_QUICKLIST                   131
#define IDS_APPLICATIONS                132
#define IDS_TYPE                        133
#define IDS_EXPIRES                     134
#define IDS_APPLICATION                 135
#define IDS_LOCATION                    136
#define IDS_STATUS                      137
#define IDS_NAME                        138
#define IDS_PATH                        139
#define IDS_NEWPROFILE                  140
#define IDS_EDITPROFILE                 141
#define IDS_DEFAULT                     142
#define IDS_ANTIP2P                     143
#define IDS_ADS                         144
#define IDS_EDU                         145
#define IDS_SPYWARE                     146
#define IDS_LEVEL1                      147
#define IDS_LEVEL2                      148
#define IDS_LEVEL3                      149
#define IDS_GAMING                      150
#define IDS_PUBLISHER                   151
#define IDS_ALLOW                       152
#define IDS_BLOCK                       153
#define IDS_BOGON                       154
#define IDS_DSHIELD                     155
#define IDS_HIJACKED                    156
#define IDS_MULTICAST                   157
#define IDS_PRIVATE                     158
#define IDS_RESERVED                    159
#define IDS_SPIDERS                     160
#define IDS_TROJANS                     161
#define IDS_LANRANGES                   162
#define IDS_BTALLOWS                    163
#define IDC_LOCATION                    1011
#define IDC_BROWSE                      1012
#define IDC_PROXY                       1014
#define IDC_PROXY_HTTP                  1015
#define IDC_PROXY_SOCKS4                1016
#define IDC_PROXY_SOCKS5                1017
#define IDC_PROXY_DEFAULT               1018
#define IDC_ALLOW                       1019
#define IDC_BLOCK                       1020
#define IDC_PRESETS                     1021
#define IDC_LISTS                       1022
#define IDC_ADD                         1023
#define IDC_PROFILES                    1024
#define IDC_REMOVE                      1025
#define IDC_EDIT                        1026
#define IDC_OPEN                        1027
#define IDC_DESCRIPTION                 1028
#define IDC_LIST                        1032
#define IDC_ADDRESS                     1033
#define IDC_EXPIREDATE                  1035
#define IDC_EXPIRETIME                  1038
#define IDC_CONTENT                     1039
#define IDC_DOPE                        1040
#define IDC_EDIT1                       1041
#define IDC_PATH                        1041
#define IDC_BUTTON1                     1042
#define IDC_LIST1                       1043
#define IDC_APPS                        1043
#define IDC_LABEL                       1044
#define IDC_LINEGRAPH                   1045
#define IDC_RENAME                      1048
#define ID_CONTEXT_ENABLEPEERGUARDIAN   40001
#define ID_CONTEXT_ENABLEPEERGUARDIAN40002 40002
#define ID_CONTEXT_DISABLEPEERGUARDIAN  40003
#define ID_CONTEXT_ENABLE               40004
#define ID_CONTEXT_ENABLEHTTP           40005
#define ID_CONTEXT_DISABLE              40006
#define ID_HELP_ABOUTPEERGUARDIAN       40007
#define ID_HELP_PEERGUARDIANHOMEPAGE    40008
#define ID_HELP_PHOENIXLABSHOMEPAGE     40009
#define ID_APPLICATION_EXIT             40010
#define ID_APPLICATION_OPTIONS          40011
#define ID_APPLICATION_LISTMANAGER      40012
#define ID_APPLICATION_ENABLEPEERGUARDIAN 40013
#define ID_APPLICATION_ENABLEPEERGUARDIAN40014 40014
#define ID_APPLICATION_DISABLEPEERGUARDIAN 40015
#define ID_APPLICATION_ENABLE           40016
#define ID_APPLICATION_ENABLEHTTP       40017

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        127
#define _APS_NEXT_COMMAND_VALUE         40018
#define _APS_NEXT_CONTROL_VALUE         1049
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
